// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/finance-layout/DarkBlue.tsx": () => import("../components/mockups/finance-layout/DarkBlue.tsx"),
  "./components/mockups/finance-layout/LightBlue.tsx": () => import("../components/mockups/finance-layout/LightBlue.tsx")
};
